<?php
 // module/Album/view/album/album/delete.phtml:

 $titre = 'Delete album';
 $this->headTitle($titre);
 ?>
 <h1><?php echo $this->escapeHtml($titre); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($album->titre); ?>' by
     '<?php echo $this->escapeHtml($album->aliments); ?>'?
 </p>
 <?php
 $url = $this->url('album', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>